### PR TITLE
Adds sass workflow

### PR DESCRIPTION
**Pull request by danielcgold**
Includes [node-sass](https://github.com/sass/node-sass). 

You can now `npm run build-css` and `npm run watch-css`. This also includes a `.scss` file so you can include it in projects if you eventually pull this in with bower or another package manager. 

high-5

### CODE REVIEW

**Comment by maxbeier** [comment]
Hi,

thanks for your work, but I hesitate to merge this.

At the moment this is a really small project, that maybe could have been a link to a CodePen demo, because it's just a CSS file, that itself is basically 14 lines of code and some lines per spinner. So I have a queasy feeling to add a pre-processor that in the end is only used for one level of nesting. And currently I neither see a need for a build script nor a watcher.

But I think I'm missing the point (and I don't know much about bower). So why do you need a Sass version? Or why can't you include the CSS version?

**Comment by danielcgold** [comment]
**First thought**
Provided a workflow for updates + have the CSS file be compressed in the end. 

**Second thought**
It's now more flexible! You could have a variable that controls the text color and have the client change the that variable. 

With bower, the user could being the stylesheet into their project and include it with import paths. Having the scss file and scss work flow would make changes easier in that future. 

Since you'd like to keep this small and there doesn't seem to be a desire to expand, feel free to close/comment!

**Comment by maxbeier** [comment]
Hmm, ok. The point I conform with is easy inclusion in Sass based systems. But I don't want to just have a renamed copy of the CSS file, so I will add a symlink. Could you try if this works for you?

**Comment by danielcgold** [comment]
I'm not sure if I follow. Sorry!

**Comment by maxbeier** [comment]
There's an scss version now, which is just a symlink to the css version. So it should be possible to `@import` it in scss and use it with bower.

**Comment by danielcgold** [comment]
oh I see your commit now. Cool this would work!

**Comment by maxbeier** [comment]
Arg, neither npm nor bower seem to bother with the symlink so this does not work. As silly as it feels, currently I don't have a better idea than to maintain a renamed copy of the CSS file.

I'm sorry to dismiss your work, but I will reduce your PR to the mentioned copy. I hope that's ok for you and thanks for you initiative! I really think it will help others.

**Comment by danielcgold** [comment]
No worries -- thanks for working with this!

**Pull request merged**
